s3fs_cors.settings:
  type: config_object
  mapping:
    s3fs_cors_origin:
      type: string
      label: 'CORS Origin'
    s3fs_https:
      type: string
      label: 'Use Https/Http'
    s3fs_access_type:
      type: string
      label: 'Access Type on File Uploads'
    s3fs_sts_policy_resource:
      type: string
      label: 'STS Policy Resource'
