taxonomies:
  tags:
    -
      vid: tags
      tid: '1'
      langcode: en
      name: 'music db'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: a3f98fda-5c64-45b6-8028-c4ea075e4837
    -
      vid: tags
      tid: '2'
      langcode: en
      name: adspender
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: cce9d6e1-8b96-4916-b345-2bef8c6ef177
    -
      vid: tags
      tid: '3'
      langcode: en
      name: tnp
      description__value: "<p>The Tennessee Newspaper Project (TNP) is part of the&nbsp;<a href=\"http://www.neh.gov/us-newspaper-program\">United States Newspaper Program</a>, a national effort to locate, catalog, preserve on microfilm, and make accessible, newspapers published in the United States from the earliest colonial days to the present. Grant funding is provided by the&nbsp;<a href=\"\">National Endowment for the Humanities</a>&nbsp;and technical support is provided by the&nbsp;<a href=\"http://www.loc.gov/\">Library of Congress</a>. Tennessee's project is based in Knoxville at the&nbsp;<a href=\"http://www.lib.utk.edu/\">University of Tennessee Libraries</a>.</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: e949cd62-47e2-4611-9c7b-ed55fba11fb8
    -
      vid: tags
      tid: '4'
      langcode: en
      name: census-ftd
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1e6c8e11-47ed-424a-bebf-09774b1f8742
    -
      vid: tags
      tid: '5'
      langcode: en
      name: chinacensus
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 5544ad2c-a0fa-4a5f-a382-460b6b113b54
    -
      vid: tags
      tid: '6'
      langcode: en
      name: cntsda
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1fa1c68b-73d6-4cac-a9b7-f7f96d61aad0
    -
      vid: tags
      tid: '7'
      langcode: en
      name: corvey
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: c37690df-ac88-45d6-9e93-9ccf3e53e67b
    -
      vid: tags
      tid: '8'
      langcode: en
      name: ejournals
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 54758246-9d19-443b-9896-49fdfaa17858
    -
      vid: tags
      tid: '9'
      langcode: en
      name: ICMA
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 349ad8d0-8ef9-46a2-8ce9-1850d3825ba6
    -
      vid: tags
      tid: '10'
      langcode: en
      name: ICRG
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 8c2188aa-24a9-4e49-8b78-430a491acc85
    -
      vid: tags
      tid: '11'
      langcode: en
      name: ITERATE
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: b9f6d3a8-af03-4f02-8c0a-c53d8ce5d243
blocks: {  }
menus:
  -
    menu_name: tools
    title: 'Music DB'
    parent: null
    uri: 'internal:/music-view'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 2d0dabdf-53bf-444d-9668-1fc6985c03d5
  -
    menu_name: tools
    title: 'Adspender DB'
    parent: null
    uri: 'internal:/adspender'
    link_title: ''
    description: null
    enabled: '0'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: e3c0f8f9-2e25-4cb4-bac5-dac50e17cf8c
  -
    menu_name: tools
    title: 'TNP DB'
    parent: null
    uri: 'internal:/tnp'
    link_title: ''
    description: 'Tennessee Newspaper Project'
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: e3b4401b-8e49-4b55-abd3-57daedd03eb3
